### ISSUE TITLE
Support for std::wstring

### ISSUE THREAD

**Issue by DelinWorks** [pulzed/mINI#16]
Hi, I write ini files in arabic paths which makes the app crash when passing a wide char* or a wstring path
Like: `C:/somefoler/مجلد/settings.ini`
Is there a feature for wstring filenames and what not?

**Comment by pulzed** [comment]
Most UTF-8 encoded strings should work I believe. But to answer your question, no, this library will use std::string only as the base type, that way it remains the most compatible with all the codebases it's used with. You can always fork the library and replace std::string with wstring internally, I don't think it should be too problematic. I've tested with unicode and sometimes it breaks, other times not. Encoding in general confuses me honestly. In any case, given the simplicity of this library and its original aims, I really don't want to complicate it any further. Sorry about that I hope you figure a good solution to your issue.

**Comment by DelinWorks** [comment]
Understandable

I looked into this function and it works fine for `std::ofstream` when passing an arabic url
but not for mINI::INIFile which is weird... I'll look internally for what INIFile does and see if I can make it work

```
    inline const char* WC2MB(const wchar_t* wstr)
    {
        int wstr_len = (int)wcslen(wstr);
        int num_chars = WideCharToMultiByte(CP_UTF8, 0, wstr, wstr_len, NULL, 0, NULL, NULL);
        char* strTo = (char*)malloc((num_chars + 1) * sizeof(char));
        if (strTo)
        {
            WideCharToMultiByte(CP_UTF8, 0, wstr, wstr_len, strTo, num_chars, NULL, NULL);
            strTo[num_chars] = '\0';
        }
        return strTo;
    }
```

**Comment by DelinWorks** [comment]
Is there a function that gives me the ini data as an std::string? I don't wnat it to write to a file so I can deal with it myself

**Comment by pulzed** [comment]
Nope. INIStructure tries to map the actual structure of an INI file. You can only query actual values as strings. INIWriter uses a vector of strings for output but even that is only so it can preserve original formatting.

**Comment by DelinWorks** [comment]
Okay thanks for the heads up! all deal with it in my fork
