### ISSUE TITLE
Cannot read ini files with utf-8 BOM encoding properly

### ISSUE THREAD

**Issue by huqng** [pulzed/mINI#17]

**Comment by pulzed** [comment]
Any examples that reproduce the behavior? I'm not sure how that would break the parser but I'm willing to look into it if you can provide some more details, preferably a testcase with the file that breaks. Thanks :)

**Comment by huqng** [comment]
Utf8BOM file has a 0xEFBBBF header. Your parser cannot read any [section] at the first line, since it doen't start with '[', trimed or not. Adding a black line before the first [section] would solve this.

**Comment by pulzed** [comment]
Yep, you're right, it fails on the first section. I'll look into it. Thanks for bringing this up.

**Comment by pulzed** [comment]
Fixed in 0.9.12. Thanks!

**Comment by pulzed** [comment]
Actually, this might still be an issue as writing back to BOM-encoded file might fail as well. Need to look into that too.

**Comment by pulzed** [comment]
Fixed now in 0.9.13.
