### ISSUE TITLE
this is the best lib for ini that i have ever tried

### ISSUE THREAD

**Issue by aurhack** [pulzed/mINI#20]

**Comment by pulzed** [comment]
That's the best kind of issue. ;) Thanks

**Comment by aurhack** [comment]
hehe, It's really good not going to lie, the only thing is that (  as far i know ), i can't check on a if statement if a key of a section contains X value, is it possible in any way?

**Comment by pulzed** [comment]
>if a key of a section contains X value, is it possible in any way?
Yep - just use the has() function, the readme documents a couple of usecases. Should get you started. :)
