### ISSUE TITLE
Trying to generate / rewrite the config only if there isn't one

### ISSUE THREAD

**Issue by thecule** [pulzed/mINI#8]
Trying to generate / rewrite the config only if there isn't one , how would I do this ? I tried using functions from the lib that return the bool but didn't help much.

**Comment by pulzed** [comment]
Hey - not sure what you mean. This library only works with strings, all type conversions are up to the user.

**Comment by pulzed** [comment]
Oh - I think I understand your question now. The `file.read()` operation should return false when the file can't be read, which normally implies that it's missing. You can also just check if the file exists before writing. Hope this helps.
